language: python
branches:
  only:
  - master
install:
- git config --global user.email "info@loadays.org"
- git config --global user.name "loadays"
- pip install pelican ghp-import Markdown
script:
- make publish github
notifications:
  irc:
    channels:
      - "irc.freenode.org#loadays"
    on_success: change
